// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACDbKfIVrMbKJnSHtylvhMPoa4tn4seI',
    appId: '1:876337617314:web:c26f1204d56b0361b8fafb',
    messagingSenderId: '876337617314',
    projectId: 'hext-care-operations',
    authDomain: 'hext-care-operations.firebaseapp.com',
    storageBucket: 'hext-care-operations.firebasestorage.app',
    measurementId: 'G-CDS0K1NC3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV1aDZ73heYFPEe1rETVJ-9Xy-LF7wM_s',
    appId: '1:876337617314:android:60cffc794739a553b8fafb',
    messagingSenderId: '876337617314',
    projectId: 'hext-care-operations',
    storageBucket: 'hext-care-operations.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTNuzWQaqhH45PA8QnEyDb2kjnY-nkFE',
    appId: '1:876337617314:ios:61419132702d675cb8fafb',
    messagingSenderId: '876337617314',
    projectId: 'hext-care-operations',
    storageBucket: 'hext-care-operations.firebasestorage.app',
    iosBundleId: 'com.gestionsalud.hext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTNuzWQaqhH45PA8QnEyDb2kjnY-nkFE',
    appId: '1:876337617314:ios:61419132702d675cb8fafb',
    messagingSenderId: '876337617314',
    projectId: 'hext-care-operations',
    storageBucket: 'hext-care-operations.firebasestorage.app',
    iosBundleId: 'com.gestionsalud.hext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACDbKfIVrMbKJnSHtylvhMPoa4tn4seI',
    appId: '1:876337617314:web:95b5c771a6b89c78b8fafb',
    messagingSenderId: '876337617314',
    projectId: 'hext-care-operations',
    authDomain: 'hext-care-operations.firebaseapp.com',
    storageBucket: 'hext-care-operations.firebasestorage.app',
    measurementId: 'G-YRBFCC7THZ',
  );
}
