// Barrios de Cartagena
const List<String> kBarriosCartagena = <String>[
  'Alameda La Victoria',
  'Albornoz',
  'Alcibia',
  'Alfredo V. Bonilla',
  'Alto Bosque',
  'Altos de San Isidro',
  'Amberes',
  'Antonio Jose de Sucre',
  'Arroz Barato',
  'Bellas Artes',
  'Bellavista',
  'Bicentenario',
  'Blas de Lezo',
  'Bocachica',
  'Bocagrande',
  'Bruselas',
  'Buenos Aires',
  'Caite',
  'Camaguey',
  'Campestre',
  'Canapote',
  'Carmen de Bolivar',
  'Castillogrande',
  'Ceballos',
  'Centro',
  'Cerros de Albornoz',
  'Chambacu',
  'Chapacua',
  'Chipre',
  'Chiquinquira',
  'Ciudad Bicentenario',
  'Ciudadela 2000',
  'Ciudadela La Paz',
  'Colinas de Villa Barraza',
  'Conjunto Portal de La Cordialidad',
  'Crespo',
  'Daniel Lemaitre',
  'El Bosque',
  'El Campestre',
  'El Carmelo',
  'El Country',
  'El Educador',
  'El Espinal',
  'El Gallo',
  'El Golf',
  'El Limonar',
  'El Milagro',
  'El Nazareno',
  'El Paraiso',
  'El Poblado',
  'El Pozon',
  'El Prado',
  'El Recreo',
  'El Rodeo',
  'El Rubi',
  'El Socorro',
  'El Uvito',
  'Escallon Villa',
  'Espana',
  'Flor del Campo',
  'Fredonia',
  'Getsemani',
  'Henequen',
  'Jose Antonio Galan',
  'Juan XXIII',
  'La Boquilla',
  'La Campina',
  'La Carolina',
  'La Castellana',
  'La Candelaria',
  'La Central',
  'La Concepcion',
  'La Consolata',
  'La Esperanza',
  'La Esmeralda I',
  'La Esmeralda II',
  'La Florida',
  'La Gloria',
  'La India',
  'La Magdalena',
  'La Maria',
  'La Matuna',
  'La Paz',
  'La Princesa',
  'La Providencia',
  'La Quinta',
  'Las Americas',
  'Las Brisas',
  'Las Delicias',
  'Las Gavias',
  'Las Gaviotas',
  'Las Palmeras',
  'Las Reinas',
  'Las Vegas',
  'Loma Fresca',
  'Los Alpes',
  'Los Almendros',
  'Los Calamares',
  'Los Caracoles',
  'Los Cerezos',
  'Los Comuneros',
  'Los Corales',
  'Los Ejecutivos',
  'Los Laureles',
  'Los Santanderes',
  'Manga',
  'Manzanillo del Mar',
  'Maria Auxiliadora',
  'Martinez Martelo',
  'Membrillal',
  'Mirador de La Bahia',
  'Mirador de San Jose',
  'Miramar',
  'Nelson Mandela',
  'Nueve de Abril',
  'Nuevo Bosque',
  'Nuevo Chile',
  'Nuevo Oriente',
  'Olaya Herrera',
  'Palmarito',
  'Paraiso II',
  'Paseo de Bolivar',
  'Pasacaballos',
  'Pedro Salazar',
  'Pie de La Popa',
  'Pie del Cerro',
  'Policarpa',
  'Portal de Alicante',
  'Portales de San Fernando',
  'Pozon Central',
  'Puerta de Hierro',
  'Puerto Rey',
  'Republica de Chile',
  'Republica del Caribe',
  'Rodeo',
  'San Antonio',
  'San Bernardo',
  'San Diego',
  'San Fernando',
  'San Francisco',
  'San Isidro',
  'San Jose de los Campanos',
  'San Jose Obrero',
  'San Pedro Martir',
  'San Pedro y Libertad',
  'San Vicente de Paul',
  'Santa Clara',
  'Santa Lucia',
  'Santa Maria',
  'Santa Monica',
  'Santa Rita',
  'Sector 11 de Noviembre',
  'Sector Rafael Nunez',
  'Siete de Agosto',
  'Torices',
  'Turbaco Urbano',
  'Urbanizacion La India',
  'Urbanizacion San Buenaventura',
  'Urbanizacion Simon Bolivar',
  'Villa Barraza',
  'Villa Corelca',
  'Villa Estrella',
  'Villa Fanny',
  'Villa Hermosa',
  'Villa Rosita',
  'Villa Sandra',
  'Villa Zuldany',
  'Villagrande de Indias',
  'Vista Hermosa',
  'Zaragocilla',
];
