const List<String> municipiosBolivar = <String>[
  'Cartagena de Indias',
  'Turbaco',
  'Arjona',
  'Turbana',
  'Santa Rosa',
  'Santa Catalina',
  'Clemencia',
  'Villanueva',
  'Mahates',
  'San Estanislao',
  'Soplaviento',
  'Calamar',
  'María La Baja',
  'San Juan Nepomuceno',
  'San Jacinto',
  'El Carmen de Bolívar',
  'Zambrano',
  'Córdoba',
  'Magangué',
  'Mompox',
];
